export const CHANGE_QUESTION_CATEGOTY = "CHANGE_QUESTION_CATEGOTY";
export const CHANGE_QUESTION_DIFFICULTY = "CHANGE_QUESTION_DIFFICULTY";
export const CHANGE_QUESTION_TYPE = "CHANGE_QUESTION_TYPE";
export const CHANGE_QUESTION_AMOUNT = "CHANGE_QUESTION_AMOUNT";
export const CHANGE_SCORE = "CHANGE_SCORE";
